Project6: Proj6main.o List.o 
	g++ -o Project6 Proj6main.o List.o

Proj6main.o: Proj6main.cpp Island.h 
	g++ -c Proj6main.cpp

List.o: List.cpp Island.h
	g++ -c List.cpp

clean:
	rm  Proj6main.o List.o Project6
